### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by TomasTomecek** [kosciCZ/release-bot#27]
* readme
  * You mention some examples -- I would create a clickable link to them directly (or maybe even show them)
  * The other thing to improve could be to do a simple guide with real examples what users need to do in order to use the bot.
  * Overall the readme is well written, detailed and nicely formatted. For me personally, it's too thick, I prefer readmes which don't have "wall of text".
* nit: you can define logger as global variable, should be easier to reference: `logger` vs `CONFIGURATION["logger"]`
* I don't see a single class defined, from structure PoV, it looks a lot like a C program; not a problem, just an observation
* I'm not familiar with the new GitHub's API: in function `get_latest_version_github()`, does it pick latest as last released?
* `shell_command()`: please make it work with `shell=False`; it's a real security risk to do `shell=True`; someone can easily drop `; rm -rf /*` into the config and do nasty things; this is a hard blocked from my PoV
* `main()` is way too long

Overall, the code looks really good, it's clear that you spent some serious time polishing it. One major thing I would improve is the structure. We'll talk in person.

**Comment by kosciCZ** [comment]
I very much appreciate the review, thank you. Quick response on some of the points, before we get a chance to talk:
>The other thing to improve could be to do a simple guide with real examples what users need to do in order to use the bot.

I agree with this, although I think I'm pushing limits of what readme should be, so maybe creating a github wiki might be a good idea.

>I don't see a single class defined, from structure PoV, it looks a lot like a C program; not a problem, just an observation

This is a very valid observation and as I started to rewrite some of the functions in order to be able to test & mock them, I realized that class structure would be more beneficial - i.e. class for PyPi, Fedora and Github would certainly made things better.

>I'm not familiar with the new GitHub's API: in function get_latest_version_github(), does it pick latest as last released?

It does, each query is also further wrapped by `send_query()`. Resulting query might look like [this](https://gist.github.com/kosciCZ/4029c7d38ceecf2600784a1c2f4aba56) and you can test it out [here](https://developer.github.com/v4/explorer/)

>main() is way too long

I agree it needs to be better structured into separate functions because right now it's not very testable and kind of a mess. 

I haven't addressed everything, this should be just a short heads up before talking in person.

**Comment by kosciCZ** [comment]
Closing, new issues were opened covering this review
